#!/usr/bin/env bash
# script that will display information about subdomains.
domain="$1"

func () {
    result=$(dig "$1"".""$domain" | grep -A1 'ANSWER SECTION:' | tr "\t" "\n" | tail -2 | tr "\n" " ") 
    echo "$1 $result" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# -eq 2 ];then
    func "$2"
elif [ $# -eq 1 ];then
    func www
    func lb-01
    func web-01
    func web-02
fi
