#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

apt-get update;
apt-get install nginx -y;
service nginx start
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
     location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
      }
}
" | tee /etc/nginx/sites-available/default
service nginx restart;
