#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get update;
apt-get install nginx -y;
service nginx start;
mkdir /var/www/html;
touch /var/www/html/404.html;
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html;

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
     location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
     }
     error_page 404 /404.html;
     location /404 {
           root /var/www/html;
           internal;
     }
}" > /etc/nginx/sites-available/default;
service nginx restart;
