#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

apt-get update;
apt-get install nginx -y;

mkdir /var/www/html;
touch /var/www/html/404.html;
echo "Ceci n'est pas une page" > /var/www/html/404.html;

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
     location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
     }
     location / {
           add_header X-Served-By $HOSTNAME;
           error_page 404 /404.html;
     }
}" > /etc/nginx/sites-available/default;
service nginx restart;
