#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

service nginx start;
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     add_header X-Served-By $HOSTNAME;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default;
service nginx restart;
