#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
echo -e "server {\n\tlisten\t80 default_server\n}" > /etc/nginx/sites-enabled/default
service nginx restart
rm /run/nginx.pid
