#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely

file=/var/run/holbertonscript.pid
echo $BASHPID > file
trap 'echo "I hate the kill command"; rm $file; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm $file; exit' SIGQUIT

x=1
while [ $x -eq 1 ]
do
echo "To infinity and beyond"
sleep 2
done
