#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times using while.

x=0
while [ $x -le 9 ]
do
  if [ $x -eq 8 ]
  then
    echo "Hi"
    x=$(( x + 1 ))
    continue
  fi
  echo "Holberton School"
  x=$(( x + 1 ))
done
