#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times using while.

x=0
while [ $x -le 9 ]
do
  echo "Holberton School"
  if [ $x -eq 8 ]
  then
    echo "Hi"
  fi
  x=$(( x + 1 ))
done
