#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times using while.

x=0
while [ $x -le 9 ]
do
  if [ $x -eq 3 ]
  then
    echo "bad luck"
    echo "Holberton School"
  elif [ $x -eq 7 ]
  then
    echo "bad luck"
    echo "Holberton School"
  else
    echo "Holberton School"
  fi
  x=$(( x + 1 ))
done
