#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times using while,
#in 4 loop print bad luck and in 8 loop print good luck.

x=0
while [ $x -le 9 ]
do
  if [ $x -eq 3 ]
  then
    echo "bad luck"
  elif [ $x -eq 7 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  x=$(( x + 1 ))
done
