#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 and:
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 4 and then bad luck from China for the 4th loop iteration


x=1
while [ $x -le 20 ]
do
  case $x in
  *)
      echo $x!
      ;;
  4)
        echo bad luck from China
      ;;
  12)
      echo bad luck from Japan
      ;;
  17)
      echo bad luck from Italy
      ;;
  esac
  x=$(( x + 1 ))
done
