#!/usr/bin/env bash
#Bash script that gives you information about the holbertonschool file.

file='holbertonschool'
if [ -a ./$file];
then
    echo "holbertonschool file exists"
    if [ -r ./$file ];
    then
      echo "holbertonschool file is not empty"
    else
      if [ -d ./$file ];
        fi
      else
        echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi
